plugins { id "com.android.application" }
android {
    namespace "com.bongorian.pocketsynth"
    compileSdk 34
    signingConfigs {
        debug {
            def existingKey = file(providers.gradleProperty('pocketDebugKeystore').getOrElse(
                System.getProperty('user.home') + '/.config/.android/debug.keystore'))
            if (existingKey.exists()) storeFile existingKey
        }
    }
    defaultConfig {
        applicationId "com.bongorian.pocketsynth"
        minSdk 26
        targetSdk 34
        versionCode 5
        versionName "5.0"
    }
}
